@base_url = http://localhost:4004/odata/v4/event

### Read all events
GET {{base_url}}/Events

### Create an event
POST {{base_url}}/Events
Content-Type: application/json

{
    "title": "SAP TechEd 2026",
    "startDate": "2026-10-15:09:00:00Z",
    "endDate": "2026-10-17:18:00:00Z"
}

### Read with $select
GET {{base_url}}/Events?$select=title,startDate

### Filter by title
GET {{base_url}}/Events?$filter=title eq 'SAP TechEd 2026'

### Sort and paginate
GET {{base_url}}/Events?$orderby=startDate desc&$top=10&$skip=0

### Read all venues
GET {{base_url}}/Venues

### Create a venue
POST {{base_url}}/Venues
Content-Type: application/json

{
    "name": "Fira Barcelona Gran Via",
    "city": "Barselona",
    "country": "Spain",
    "streetAddress": "Av. Joan Carles I, 64",
    "postalCode": "08908",
    "capacity": 15000
}

